version: 0.0
os: linux
files:
  - source: /
    destination: /opt/mindo/app
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: deploy/stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: deploy/validate.sh
      timeout: 120
      runas: root
